# Generated by Django 6.0.3 on 2026-06-25 03:09

import Inventario.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80, unique=True, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre de la Categoría')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('BEBIDA', 'Bebida')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['tipo', 'nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras])),
                ('cantidad_insumo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos (g)'), ('kg', 'Kilogramos (kg)'), ('ml', 'Mililitros (ml)'), ('und', 'Unidades')], default='g', max_length=20)),
                ('precio_insumo', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre_insumo'],
            },
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id_bebida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bebida', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras])),
                ('tamaño_bebida', models.CharField(choices=[('350ml', '350 ml'), ('500ml', '500 ml'), ('1L', '1 Litro'), ('1.5L', '1.5 Litros'), ('2L', '2 Litros'), ('3L', '3 Litros'), ('Personal', 'Personal'), ('Otro', 'Otro')], max_length=20)),
                ('cantidad_bebida', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_compra', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bebidas', to='Inventario.categoria')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nombre_bebida'],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_merma', models.DateTimeField(auto_now_add=True)),
                ('cantidad_mermada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(choices=[('Caducado', 'Caducado'), ('Dañado', 'Dañado'), ('Error preparación', 'Error en preparación'), ('Robo / Pérdida', 'Robo o pérdida'), ('Otro', 'Otro')], max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_insumo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total_merma', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsable', models.CharField(max_length=100)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='Inventario.insumo')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'ordering': ['-fecha_merma'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras])),
                ('precio_producto', models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_receta', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='Inventario.producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_recetas', to='Inventario.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.recetaproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
                'unique_together': {('receta', 'insumo')},
            },
        ),
    ]
