# Generated by Django 6.0.3 on 2026-04-09 18:54

import Inventario.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id_bebida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bebida', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre de la Bebida')),
                ('cantidad_bebida', models.PositiveIntegerField(validators=[Inventario.models.validar_cantidad_positiva], verbose_name='Cantidad en Stock')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Venta')),
                ('tipo_bebida', models.CharField(max_length=50, verbose_name='Tipo de Bebida')),
                ('tamaño_bebida', models.CharField(max_length=20, verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nombre_bebida'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras, django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre del Insumo')),
                ('cantidad_insumo', models.PositiveIntegerField(validators=[Inventario.models.validar_cantidad_positiva], verbose_name='Cantidad')),
                ('precio_insumo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Compra')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre_insumo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre del Producto')),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio de Venta')),
                ('ingrediente_producto', models.CharField(blank=True, max_length=200, verbose_name='Ingredientes (temporal)')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
