# Generated by Django 6.0.3 on 2026-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Máximo'),
        ),
    ]
