# Generated by Django 6.0.3 on 2026-06-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_gramo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio Gramo'),
        ),
    ]
