# Generated by Django 6.0.3 on 2026-06-26 03:07

import Inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_insumo_stock_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre_insumo',
            field=models.CharField(max_length=100, unique=True, validators=[Inventario.models.validar_solo_letras]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Stock Máximo'),
        ),
    ]
