# Generated by Django 6.0.3 on 2026-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_insumo_precio_gramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='insumo_snapshot',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
