# Generated by Django 6.0.3 on 2026-05-20 02:44

import Inventario.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_auto_20260513_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='cantidad_bebida',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nombre_bebida',
            field=models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='tamaño_bebida',
            field=models.CharField(choices=[('350ml', '350 ml'), ('500ml', '500 ml'), ('1L', '1 Litro'), ('1.5L', '1.5 Litros'), ('2L', '2 Litros'), ('3L', '3 Litros'), ('Personal', 'Personal'), ('Otro', 'Otro')], max_length=20, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=80, unique=True, validators=[Inventario.models.validar_solo_letras, django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_insumo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre_insumo',
            field=models.CharField(max_length=100, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre del Insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_insumo',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ingrediente_producto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio de Venta'),
        ),
    ]
