# Generated by Django 6.0.3 on 2026-05-20 02:54

import Inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_bebida_cantidad_bebida_alter_bebida_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='tipo_bebida',
            field=models.CharField(max_length=50, validators=[Inventario.models.validar_solo_letras], verbose_name='Tipo de Bebida'),
        ),
    ]
