# Generated by Django 6.0.3 on 2026-06-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_insumo_nombre_insumo_alter_insumo_stock_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='Inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('BEBIDA', 'Bebida'), ('INSUMO', 'Insumo')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos (g)'), ('und', 'Unidades')], default='g', max_length=20),
        ),
    ]
