# Generated by Django 6.0.3 on 2026-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_merma_insumo_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_a_agregar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='merma',
            name='insumo_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
