# Generated by Django 6.0.3 on 2026-06-04 03:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_bebida_tipo_bebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos (g)'), ('kg', 'Kilogramos (kg)'), ('ml', 'Mililitros (ml)'), ('und', 'Unidades')], default='g', max_length=20, verbose_name='Unidad de Medida'),
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_receta', models.TextField(blank=True, null=True, verbose_name='Descripción / Instrucciones de preparación')),
                ('activa', models.BooleanField(default=True, verbose_name='Receta Activa')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='Inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Requerida')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_recetas', to='Inventario.insumo', verbose_name='Insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Inventario.recetaproducto', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
                'unique_together': {('receta', 'insumo')},
            },
        ),
    ]
