# Generated by Django 6.0.3 on 2026-06-30 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_insumo_cantidad_a_agregar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='cantidad_a_agregar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad adicional'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_a_agregar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_insumo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
