# Generated by Django 6.0.3 on 2026-06-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_insumo_categoria_alter_categoria_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='recetaproducto',
            name='descripcion_receta',
        ),
        migrations.AddField(
            model_name='bebida',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='tamaño_bebida',
            field=models.CharField(choices=[('350ml', '350 ml'), ('500ml', '500 ml'), ('1L', '1 Litro'), ('1.5L', '1.5 Litros'), ('2L', '2 Litros'), ('Personal', 'Personal'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='merma',
            name='costo_total_merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='merma',
            name='precio_insumo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
