# Generated by Django 6.0.3 on 2026-06-27 05:03

import Inventario.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_remove_insumo_categoria_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80, unique=True, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre de la Categoría')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('BEBIDA', 'Bebida'), ('INSUMO', 'Insumo')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['tipo', 'nombre_categoria'],
            },
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='nombre_categoria',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre_categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_categoria',
        ),
        migrations.AddField(
            model_name='bebida',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bebidas', to='Inventario.categoria'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='Inventario.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Inventario.categoria'),
        ),
    ]
