# Generated by Django 6.0.3 on 2026-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_bebida_cantidad_a_agregar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='bajo_stock_30',
            field=models.PositiveIntegerField(default=5, verbose_name='Bajo Stock 30%'),
        ),
    ]
