# Generated by Django 6.0.3 on 2026-06-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_insumo_unidad_medida_recetaproducto_detallereceta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingrediente_producto',
        ),
    ]
