# Generated by Django 6.0.3 on 2026-06-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_categoria_remove_bebida_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
