# Generated by Django 6.0.3 on 2026-07-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_bebida_bajo_stock_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='precio_unitario_compra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Precio Unitario Compra'),
        ),
        migrations.AddField(
            model_name='bebida',
            name='precio_unitario_venta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Precio Unitario Venta'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='bajo_stock_30',
            field=models.PositiveIntegerField(default=0, verbose_name='Bajo Stock 30%'),
        ),
    ]
