# Generated by Django 6.0.3 on 2026-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_bebida_precio_unitario_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='bajo_stock_30',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Bajo Stock 30%'),
        ),
    ]
