# Generated by Django 6.0.3 on 2026-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_bebida_bajo_stock_30'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='bajo_stock_30',
        ),
        migrations.AddField(
            model_name='bebida',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
