# Generated by Django 6.0.3 on 2026-07-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_remove_bebida_bajo_stock_30_bebida_stock_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio_gramo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Gramo'),
        ),
    ]
