# Generated by Django 6.0.3 on 2026-07-14 00:36

import Inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_alter_bebida_precio_compra_alter_bebida_precio_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=100, unique=True, validators=[Inventario.models.validar_solo_letras], verbose_name='Nombre de la Categoría'),
        ),
    ]
