# Generated by Django 6.0.3 on 2026-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_alter_categoria_nombre_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_a_agregar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
