# Generated by Django 6.0.3 on 2026-07-14 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_alter_insumo_cantidad_a_agregar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebida',
            name='precio_unitario_compra',
        ),
        migrations.RemoveField(
            model_name='bebida',
            name='precio_unitario_venta',
        ),
        migrations.AddField(
            model_name='bebida',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='cantidad_requerida',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
