# Generated by Django 6.0.3 on 2026-07-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_bebida_costo_unitario_refactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebida',
            old_name='precio_venta',
            new_name='precio_unitario_venta',
        ),
    ]
