# Generated by Django 6.0.3 on 2026-07-01 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.PositiveIntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['numero_mesa'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_insumo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('usar', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.insumo', verbose_name='Insumos Utilizados')),
                ('detalle_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='Gestion_Pedidos.detallepedidoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inventario_descontado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Mesa', 'Mesa'), ('Recoger', 'Recoger'), ('Domicilio', 'Domiilio')], default='Mesa', max_length=20)),
                ('tipo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En cocina', 'En cocina'), ('', 'Cocinado'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('direccion_pedi', models.CharField(blank=True, max_length=150, null=True, verbose_name='')),
                ('nombre_cliente', models.CharField(blank=True, max_length=70, verbose_name='Nombre del cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Gestion_Pedidos.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallepedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Gestion_Pedidos.pedido'),
        ),
        migrations.CreateModel(
            name='DetallePedidoBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventario.bebida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bebidas', to='Gestion_Pedidos.pedido')),
            ],
        ),
    ]
