# Generated by Django 6.0.3 on 2026-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0002_alter_detallepedidobebida_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En cocina', 'En cocina'), ('Cocinado', 'Cocinado'), ('Pagado', 'Pagado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Mesa', 'Mesa'), ('Recoger', 'Recoger'), ('Domicilio', 'Domicilio')], default='Mesa', max_length=20),
        ),
    ]
