# Generated by Django 6.0.3 on 2026-07-12 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0003_alter_pedido_estado_alter_pedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='minutos_recogida',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo pactado de recogida (minutos)'),
        ),
    ]
