# Generated by Django 6.0.3 on 2026-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0006_alter_detallepedidobebida_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=14, verbose_name='Teléfono del cliente'),
        ),
    ]
