# Generated by Django 6.0.3 on 2026-07-14 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0007_alter_pedido_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidobebida',
            name='costo_unitario_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
