# Generated by Django 6.0.3 on 2026-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_modify_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
