# Generated by Django 6.0.3 on 2026-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_modify_django', '0003_recuperacioncontrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
